const images = {
  Logo: require('../Components/Image/logo.png'),
  Regularisation:require('../Components/Image/regularisation.png'),
  //Login Screen
  backImage: require('../Components/Image/bbgg.png'),
  profile: require('../Components/Image/editimgBack.png'),
  eye: require('../Components/Image/eye.png'),
  hidden: require('../Components/Image/hidden.png'),
  padlock: require('../Components/Image/padlock.png'),
  email: require('../Components/Image/email.png'),
  Userprofile: require('../Components/Image/dp.png'),
  // logo: require('../Components/Image/dp.png'),
  home: require('../Components/Image/home.png'),
  sand: require('../Components/Image/sand-clock.png'),
  person: require('../Components/Image/person.png'),
  bannerrr: require('../Components/Image/bannerrr.png'),
  Backg: require('../Components/Image/backbg.png'),
  Clock: require('../Components/Image/Clock.png'),
  Location: require('../Components/Image/Location.png'),
  Rectangl: require('../Components/Image/Rectangl.png'),
  Cake: require('../Components/Image/Cake.png'),
  Balloons: require('../Components/Image/Balloons.png'),
  ///forgot
  imagebackGround1: require('../Components/Image/backGround.png'),
  Back: require('../Components/Image/Path.png'),
  Adjust: require('../Components/Image/adjust.png'),

  Menu: require('../Components/Image/Menu.png'),
  Primetime: require('../Components/Image/Primetime.png'),
  Clipboard: require('../Components/Image/Clipboard.png'),
  Bills: require('../Components/Image/Bills.png'),
  Research: require('../Components/Image/Research.png'),
  List: require('../Components/Image/List.png'),

  noti: require('../Components/Image/noti.png'),
  Plus: require('../Components/Image/Plus.png'),
  Profile: require('../Components/Image/Profile.png'),
  PhusHide: require('../Components/Image/PhusHide.png'),

  Vectorgreen: require('../Components/Image/Vectorgreen.png'),
  Vectorred: require('../Components/Image/Vectorred.png'),
  clockyellow: require('../Components/Image/clockyellow.png'),
  Approve: require('../Components/Image/greenapprov.png'), //js/Components/Image/greenapprov.png
  red: require('../Components/Image/red.png'),
  Vectoyellooo: require('../Components/Image/yellowapprov.png'),

  down: require('../Components/Image/down.png'),
  Vector: require('../Components/Image/Vector.png'),
  watch: require('../Components/Image/watch.png'),

  Approvedd: require('../Components/Image/Approve.png'),
  Reject: require('../Components/Image/Reject.png'),

  Contact: require('../Components/Image/Contact.png'),
  Locationp: require('../Components/Image/Locationp.png'),
  Lock: require('../Components/Image/Lock.png'),
  Payslip: require('../Components/Image/Payslip-Icon.png'),

  phone: require('../Components/Image/phone.png'),
  map: require('../Components/Image/map_svgrepo.com.png'),
  Page: require('../Components/Image/Page-1.png'),
  buttonn: require('../Components/Image/buttonn.png'),
  buttonnBacl: require('../Components/Image/buttonnBacl.png'),

  ///Ejoin
  hrontips: require('../Components/Image/hrontips-white.png'),
  Grouplogout: require('../Components/Image/Grouplogout.png'),
  sign: require('../Components/Image/sign.png'),
  arrow: require('../Components/Image/arrow-right-circle_svgrepo.com.png'),
  Download: require('../Components/Image/Download.png'),
  Tick: require('../Components/Image/Tick.png'),
  ring: require('../Components/Image/ring.png'),
  Group: require('../Components/Image/Group.png'),
  uploadd: require('../Components/Image/uploadd.png'),
  Done: require('../Components/Image/Done.png'),
  Goo: require('../Components/Image/Goo.png'),
  homeimage: require('../Components/Image/homeimage.png'),
  startt: require('../Components/Image/startt.png'),
  lastImage: require('../Components/Image/lastImage.png'),
  loginback: require('../Components/Image/loginback.png'),
  Groupllot: require('../Components/Image/Groupllot.png'),
  teamtracker: require('../Components/Image/teamtracker.png'),
  Leaveapproval: require('../Components/Image/approval.png'),
  DDSSRR: require('../Components/Image/ddssrr.png'),
  Rted: require('../Components/Image/Rted.png'),
  gted: require('../Components/Image/gted.png'),
  backgroundBack: require('../Components/Image/backgroundBack.png'),
  User: require('../Components/Image/user.png'),
  Leavee: require('../Components/Image/leave.png'),
  Canle: require('../Components/Image/canle.png'),
  promoter: require('../Components/Image/promoter.png'),
  fireWork: require('../Components/Image/firework.png'),
  darkBackGround: require('../Components/Image/darkBackLogin2.png'),
};

export default images;
